<?php
/**
 * @file
 * top_features_product.features.inc
 */

/**
 * Implements hook_node_info().
 */
function top_features_product_node_info() {
  $items = array(
    'product' => array(
      'name' => t('Product'),
      'base' => 'node_content',
      'description' => '',
      'has_title' => '1',
      'title_label' => t('Title'),
      'help' => '',
    ),
  );
  drupal_alter('node_info', $items);
  return $items;
}
